/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.CardLayout;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;

/**
 *
 * @author LENOVO
 */
public class PilihGambarButtonFullScreen extends javax.swing.JFrame {

    /**
     * Creates new form PilihGambarButton
     */
    public PilihGambarButtonFullScreen() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagePanel = new javax.swing.JPanel();
        Lbjadwal2 = new javax.swing.JLabel();
        Lbjadwal3 = new javax.swing.JLabel();
        Lbgrub = new javax.swing.JLabel();
        buttonPanel = new javax.swing.JPanel();
        Btngrub = new javax.swing.JButton();
        Btnjadwal2 = new javax.swing.JButton();
        Btnjadwal3 = new javax.swing.JButton();
        BtnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);

        imagePanel.setLayout(new java.awt.CardLayout());

        Lbjadwal2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lbjadwal2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/jadwal2.jpeg"))); // NOI18N
        Lbjadwal2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        imagePanel.add(Lbjadwal2, "1");

        Lbjadwal3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lbjadwal3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/jadwal3.jpg"))); // NOI18N
        Lbjadwal3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        imagePanel.add(Lbjadwal3, "2");

        Lbgrub.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lbgrub.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/grub.jpg"))); // NOI18N
        Lbgrub.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Lbgrub.setPreferredSize(new java.awt.Dimension(316, 400));
        imagePanel.add(Lbgrub, "0");

        getContentPane().add(imagePanel, java.awt.BorderLayout.CENTER);

        Btngrub.setText("grub");
        Btngrub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtngrubActionPerformed(evt);
            }
        });
        buttonPanel.add(Btngrub);

        Btnjadwal2.setText("jadwal");
        Btnjadwal2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btnjadwal2ActionPerformed(evt);
            }
        });
        buttonPanel.add(Btnjadwal2);

        Btnjadwal3.setText("jadwal fase");
        Btnjadwal3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btnjadwal3ActionPerformed(evt);
            }
        });
        buttonPanel.add(Btnjadwal3);

        BtnExit.setText("Exit");
        BtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExitActionPerformed(evt);
            }
        });
        buttonPanel.add(BtnExit);

        getContentPane().add(buttonPanel, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btnjadwal2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btnjadwal2ActionPerformed
        CardLayout cl = (CardLayout) (imagePanel.getLayout());
        cl.show(imagePanel,"1");
    }//GEN-LAST:event_Btnjadwal2ActionPerformed

    private void BtngrubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtngrubActionPerformed
        CardLayout cl = (CardLayout) (imagePanel.getLayout());
        cl.show(imagePanel,"0");
    }//GEN-LAST:event_BtngrubActionPerformed

    private void Btnjadwal3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btnjadwal3ActionPerformed
        CardLayout cl = (CardLayout) (imagePanel.getLayout());
        cl.show(imagePanel,"2");
    }//GEN-LAST:event_Btnjadwal3ActionPerformed

    private void BtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BtnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PilihGambarButtonFullScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PilihGambarButtonFullScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PilihGambarButtonFullScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PilihGambarButtonFullScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PilihGambarButtonFullScreen fullFrame = new PilihGambarButtonFullScreen();
                GraphicsDevice device = 
                        GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice();
                device.setFullScreenWindow(fullFrame);
                
                fullFrame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnExit;
    private javax.swing.JButton Btngrub;
    private javax.swing.JButton Btnjadwal2;
    private javax.swing.JButton Btnjadwal3;
    private javax.swing.JLabel Lbgrub;
    private javax.swing.JLabel Lbjadwal2;
    private javax.swing.JLabel Lbjadwal3;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JPanel imagePanel;
    // End of variables declaration//GEN-END:variables
}
